import type { Category } from './board';

// Secret questions ('custom') are written by players, not drawn from this bank.
const bank: Record<Exclude<Category, 'custom'>, string[]> = {
	fun: [
		'If we could teleport to each other right now, what is the first thing we would do?',
		'What song reminds you of me, and why?',
		'If we had a couple name, what would it be?',
		'What is the weirdest thing you have eaten this week?',
		'Which fictional couple are we most like?',
		'If you could swap lives with me for a day, what would you do first?',
		'What emoji best describes how you feel about me today?',
		'What would our pet be named if we adopted one together tomorrow?',
		'What is your most-used phrase when you text me?',
		'If our relationship was a movie, what would the title be?',
		'What is one thing in your room right now that reminds you of me?',
		'Describe your perfect lazy Sunday with me in three words.',
		"What is the most random thing that made you think of me this week?",
		"If we swapped phones for a day, what would surprise you most on mine?",
		"What would our reality TV show be called?",
		"Which snack would you mail me right now if you could?",
		"If we were a duo of superheroes, what would our powers be?",
		"What is the funniest autocorrect or typo you have ever sent me?",
		"What song should be playing when we finally see each other again?",
		"If you could teleport one food from your city to me, what would it be?",
		"What is a silly nickname you have secretly considered calling me?",
		"Which cartoon character am I most like?",
		"If we opened a tiny caf\u00e9 together, what would be on the menu?",
		"What would you name our first houseplant?",
		"What is your best impression of me? Describe it (or do it on a call later)!",
		"If we had matching tattoos, what would they be?",
		"Which theme park ride describes our relationship?",
		"What is the weirdest dream you have had about us?",
		"If our relationship had a theme song, who would sing it?",
		"What would you do if you woke up as me tomorrow?",
		"What is the most useless talent you have?",
		"Which three emojis describe your day today?",
		"If we were stuck on a desert island, what three things would you bring for us?",
		"What dance move would you show off at our wedding?",
		"Which fictional world would you want us to live in for a week?",
		"What is the best thing you have eaten this month?",
		"If you could rename me, what would you call me?",
		"What is the cheesiest pickup line you know? Use it on me.",
		"If we had a secret handshake, describe it.",
		"What would our couple Halloween costume be?",
		"Which movie would we star in together, and who plays who?",
		"What is something small that made you smile today?",
		"If you could plan a surprise video-call date, what would we do?",
		"What would be on the cover of a magazine about us?",
		"What is your go-to song when you miss me?",
		"If we were animals, which two would we be?"
	],
	deep: [
		'What is something you have never told me but want me to know?',
		'When do you miss me the most during the day?',
		'What is one fear you have about our distance, and how can I help with it?',
		'What makes you feel most loved when we are apart?',
		'What is one thing I do that makes the distance easier?',
		'How have you grown since we started dating?',
		'What does "home" mean to you now?',
		'What is a small habit of mine that you secretly love?',
		'When was the last time you cried, and what was it about?',
		'What do you need more of from me right now?',
		'What part of yourself are you still learning to love?',
		'What is a promise you want us to keep no matter what?',
		"What is something you have learned about yourself through our long-distance relationship?",
		"When do you feel closest to me even though we are apart?",
		"What is a dream you have never said out loud?",
		"How do you know when I am having a hard day, even from far away?",
		"What is a fear you have about the future that you want to share?",
		"What does a perfect apology look like to you?",
		"What part of our relationship are you most proud of?",
		"What is one thing you wish I understood better about you?",
		"What makes you feel safe with me?",
		"What is the kindest thing someone has ever done for you?",
		"How has your idea of love changed since we met?",
		"What do you need from me when you are stressed?",
		"What is something you are still healing from?",
		"What value do you hope we always share?",
		"When was the last time you felt really proud of yourself?",
		"What is something you want to forgive yourself for?",
		"What does trust mean to you?",
		"What is a moment you felt truly seen by me?",
		"How do you recharge when you feel empty?",
		"What is one way I can love you better from far away?",
		"What is a belief you held strongly that has changed?",
		"What would you want me to remember about you if we were apart for a long time?",
		"What is a small daily habit of mine that comforts you?",
		"What does home feel like, not look like?",
		"What is something you are afraid to ask me?",
		"How do you want us to handle our arguments?",
		"What is one thing you would like us to do more often?",
		"What is the hardest part of missing me, honestly?",
		"What do you think we do really well as a couple?",
		"What are you grateful for this week?",
		"What is a goal you want me to cheer you on for?",
		"What is something that always makes you feel loved, no matter what?",
		"What scares you about being vulnerable?",
		"What do you think makes our love unique?"
	],
	memory: [
		'What was your very first impression of me?',
		'What is your favourite memory of us together in person?',
		'What was the moment you realised you liked me?',
		'Which of our video calls do you remember the most, and why?',
		'What is the funniest thing that has happened between us?',
		'What did you think after our first goodbye at the airport/station?',
		'What is a gift or message from me that you still keep?',
		'What was the hardest moment for us, and what did we learn from it?',
		'Which photo of us is your favourite?',
		'What is an inside joke of ours that still makes you laugh?',
		'What is the best date we have ever had?',
		'What was the first thing you noticed about me when we finally met?',
		"What is the first song you remember us sharing?",
		"What was the very first message you sent me, and why that?",
		"What is a moment with me you replay in your head?",
		"What did you think the first time you heard my voice?",
		"What is the best gift I have ever given you?",
		"Which of our trips or visits was the most memorable?",
		"What is a time I made you laugh so hard you cried?",
		"What was the first meal we ever shared?",
		"What is a moment you knew we were going to be okay?",
		"What is your favourite photo of me, and why?",
		"What was our most awkward moment?",
		"What is the longest call we have ever had, and what did we talk about?",
		"What is something I said once that stuck with you?",
		"What was the hardest goodbye for you?",
		"What is a small moment with me that you will never forget?",
		"What was your favourite surprise from me?",
		"When did you first tell someone about me, and what did you say?",
		"What is a place that reminds you of us?",
		"What was the first thing you noticed about my personality?",
		"What is your favourite memory of us being silly?",
		"What is a memory of us that smells like something?",
		"What was the first time you felt butterflies because of me?",
		"Which of our dates would you relive tomorrow?",
		"What is a song that will always remind you of a specific moment with me?",
		"What is the funniest misunderstanding we have had?",
		"What did you think of me after our first real conversation?",
		"What is the most romantic thing I have done?",
		"What is a time I took care of you?",
		"What is the first inside joke we ever had?",
		"What was the moment you realised you missed me for the first time?",
		"What is the best video call we have ever had?",
		"What is a moment you were proud to be with me?",
		"What did our first in-person hug feel like?"
	],
	future: [
		'Which city would you love us to live in together?',
		'What is the first trip we should take once we close the distance?',
		'Describe a normal weekday morning when we finally live together.',
		'What tradition do you want us to start?',
		'What is something you want to learn together?',
		'Where do you see us in five years?',
		'What is the first meal you want to cook together in our own kitchen?',
		'What is one thing on your bucket list that you want to do with me?',
		'How do you imagine our next reunion?',
		'What would our dream home look like?',
		'What countdown are you looking forward to the most?',
		'What do you want our love to look like when we are old?',
		"What is the first thing you want us to buy for our home?",
		"Where would you love to spend a holiday season together?",
		"What does our ideal weekend morning look like in five years?",
		"What is a skill you want us to learn as a couple?",
		"Which city or country should we explore together first?",
		"What kind of pets do you imagine us having?",
		"What is one tradition from your family you want us to keep?",
		"How do you picture our first night living in the same place?",
		"What would our dream kitchen have in it?",
		"What kind of garden or balcony would we have?",
		"What is something you want to celebrate together next year?",
		"What would you want our home to smell like?",
		"What hobby do you want us to share when we live together?",
		"What is a goal you want us to reach together this year?",
		"How would you plan our next anniversary?",
		"What is a big adventure you want us to have?",
		"What do you imagine our friends saying about us in ten years?",
		"What would our ideal Sunday look like when we are old?",
		"Where would you love us to retire?",
		"What would you want our first road trip playlist to include?",
		"What is a dish you want to learn to cook for me?",
		"How do you want to decorate our first place?",
		"What is one thing you want to do the moment we close the distance?",
		"What does a perfect ordinary Tuesday together look like?",
		"What is a cause or project you would love us to support together?",
		"What is something you want us to never stop doing?",
		"Which concert or show should we see together?",
		"What would our house rules be?",
		"What is a place on your bucket list you only want to see with me?",
		"How should we celebrate when the distance is finally over?",
		"What do you hope we are like as an old couple?",
		"What is a small luxury you want in our future home?",
		"What is the next milestone you are excited for?"
	],
	ladder: [
		'You climbed a ladder! Give your partner three genuine compliments.',
		'Ladder! Tell your partner one thing they did recently that made you proud.',
		'Ladder! Describe your partner in a sentence that would make them blush.',
		'Ladder! What is something about your partner that you brag about to friends?',
		'Ladder! Write your partner a tiny two-line love poem.',
		'Ladder! What is the best thing your partner has ever said to you?',
		'Ladder! Which of your partner\'s qualities do you hope you share someday?',
		'Ladder! Finish the sentence: "I fell for you because…"',
		"Ladder! Tell your partner the moment you knew they were special.",
		"Ladder! What is one thing your partner does better than anyone you know?",
		"Ladder! Thank your partner for something they probably do not know they did.",
		"Ladder! What is your favourite thing about your partner's voice?",
		"Ladder! Describe your partner's smile in three words.",
		"Ladder! What is a way your partner has made you a better person?",
		"Ladder! Tell your partner what you admire about how they handle hard days.",
		"Ladder! What is the sweetest thing your partner has done from far away?",
		"Ladder! Give your partner a compliment you have never said before.",
		"Ladder! What makes your partner the perfect partner for you?",
		"Ladder! Tell your partner one thing you are proud of them for this month.",
		"Ladder! What is your favourite physical feature of your partner?",
		"Ladder! Describe your partner to a stranger in one sentence.",
		"Ladder! What do you love about the way your partner loves you?",
		"Ladder! Which of your partner's habits do you find adorable?",
		"Ladder! Tell your partner why they are worth the distance.",
		"Ladder! What is a word that perfectly sums up your partner?"
	],
	snake: [
		'Snake! Confess something silly you did and never told your partner.',
		'Snake! What is a little thing your partner does that annoys you (lovingly)?',
		'Snake! When was the last time you were jealous, and why?',
		'Snake! Confess the most embarrassing thing you have searched for online.',
		'Snake! What is one time you pretended to be fine but were not?',
		'Snake! What is something you overthink about in our relationship?',
		'Snake! Admit a white lie you told your partner.',
		'Snake! What is a habit of yours you know drives your partner a bit crazy?',
		"Snake! What is the pettiest thing you have ever been annoyed about with your partner?",
		"Snake! Confess a time you stalked your partner's old photos.",
		"Snake! What is something you pretend to like for your partner?",
		"Snake! What is the worst gift you have ever received and kept quiet about?",
		"Snake! Admit the longest you have gone without replying on purpose.",
		"Snake! What is a song you secretly love but are embarrassed about?",
		"Snake! What is one thing you would change about how we text?",
		"Snake! Confess the silliest thing you have cried about recently.",
		"Snake! What is something you have done that you hope your partner never finds out?",
		"Snake! What is the most dramatic you have ever been over something small?",
		"Snake! Admit a bad habit you have picked up since we started dating.",
		"Snake! What is a time you laughed at the wrong moment?",
		"Snake! What is your partner's most annoying habit on video calls?",
		"Snake! What is the strangest thing you have Googled about relationships?",
		"Snake! Confess something you have lied about to look cool.",
		"Snake! What is a food your partner loves that you secretly dislike?",
		"Snake! What is a time you were secretly glad a call ended early?"
	],
	finale: [
		'You reached the finish! Tell your partner what you love most about them, from the heart.',
		'Finish line! Make a promise to your partner for your next reunion.',
		'Finish line! Describe the moment you are most looking forward to with your partner.',
		"Finish line! What is your favourite answer your partner gave tonight?",
		"Finish line! Plan our next video date, right now, in detail.",
		"Finish line! Tell your partner one thing you will do this week to feel closer.",
		"Finish line! What did you learn about your partner in this game?",
		"Finish line! Send your partner a promise for the next time you see them.",
		"Finish line! What is a word that describes how you feel about your partner right now?",
		"Finish line! Write a one-line love note your partner can screenshot."
	],
	// Guess tiles: {their}/{they}/{them} become "your/you/you" for the subject and the subject's name for the guesser.
	guess: [
		"What is {their} go-to comfort food?",
		"What would {they} order at a coffee shop?",
		"Which song would {they} sing at karaoke?",
		"What is {their} biggest pet peeve?",
		"Where would {they} go on a dream holiday?",
		"What was {their} favourite subject at school?",
		"What is {their} hidden talent?",
		"Which animal would {they} be?",
		"What is {their} favourite movie of all time?",
		"What would {they} name a pet goldfish?",
		"What is {their} most-used app?",
		"What is {their} love language?",
		"What would {they} do with a surprise free day?",
		"What colour would {they} paint a bedroom?",
		"What is {their} biggest fear?",
		"Which celebrity would {they} love to have dinner with?",
		"What would {they} cook to impress someone?",
		"What is {their} favourite season?",
		"What is {their} dream job if money didn't matter?",
		"How would {they} order eggs at breakfast?",
		"What would {their} last meal be?",
		"What is {their} guilty-pleasure TV show?",
		"What would {they} spend a surprise $1,000 on?",
		"Which emoji would {they} use the most?",
		"What is {their} favourite way to relax after a long day?",
		"What would {they} be famous for?",
		"What is {their} ideal date night?",
		"Which three words describe {them} best?",
		"What would {they} never eat, no matter what?",
		"What is {their} favourite smell?",
		"What was {their} childhood dream job?",
		"Which country would {they} move to tomorrow?",
		"What is {their} usual morning drink?",
		"What would {they} do first at our next reunion?",
		"What is {their} most treasured possession?",
		"What makes {them} laugh the hardest?",
		"Who is {their} favourite musician right now?",
		"What is {their} favourite pizza topping?",
		"What would {they} grab first if the house was on fire (people and pets are safe)?",
		"What is {their} favourite holiday of the year?",
		"What would {their} superpower be?",
		"What is {their} go-to excuse to stay in bed?",
		"Which fictional character would {they} want as a best friend?",
		"What is {their} favourite thing to wear on a lazy day?",
		"What would {they} title {their} autobiography?"
	]
};

export type Question = { id: number; category: Category; text: string };

/** Playful forfeits for a missed guess, done by the person who guessed. */
export const FORFEITS = [
	'Send a voice note singing the chorus of "your" song.',
	'Send your silliest selfie — no retakes.',
	'Record a voice note listing three things you love about them.',
	'Do your best impression of them on your next call.',
	'Send them the cheesiest pickup line you can think of.',
	'Write them a four-line poem about their eyebrows.',
	'Send a photo of what you are wearing right now.',
	'Tell them an embarrassing story they have not heard yet.',
	'Change your phone wallpaper to a photo of them for a day.',
	'Send a voice note of your most dramatic "I miss you".',
	'Describe your perfect date with them using only emojis.',
	'Let them pick your profile picture for the next 24 hours.',
	'Send a voice note reading your last text to them like a movie trailer.',
	'Draw a portrait of them in 60 seconds and send it.',
	'Compliment them in a foreign accent of their choosing.',
	'Send them a song that reminds you of them, with a reason why.',
	'Text them "good morning" first, three days in a row.',
	'Name five things in your room that remind you of them.'
];

export const QUESTIONS: Question[] = Object.entries(bank).flatMap(([category, texts], ci) =>
	texts.map((text, i) => ({ id: ci * 100 + i, category: category as Category, text }))
);
